version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017" # Expose MongoDB on port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root # Todo: change this
      MONGO_INITDB_ROOT_PASSWORD: rootpassword # Todo: change this
      MONGO_INITDB_DATABASE: developer_database # Todo: change this
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_container
    ports:
      - "8081:8081" # Access Mongo Express at http://localhost:8083
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root # Todo: change this
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword # Todo: change this
    depends_on:
      - mongo
    networks:
      - mongo_network

volumes:
  mongo_data:

networks:
  mongo_network:
    driver: bridge
