
server:
  port: 8085

# defines routes:
# /developers is mapped to the developer service
# /projects is mapped to the project service

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: DEVELOPER-SERVICE
          uri: lb://DEVELOPER-SERVICE
          predicates:
            - Path=/developers/**
        - id: PROJECT-SERVICE
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/projects/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost